---
title: "An Agenda for Open Science in Communication"
subtitle: "Additional analyses"
output:
  html_document:
    df_print: paged
---

```{r warning=F, message=F, include=F}
library(esc); library(magrittr); library(pwr); library(tidyverse)
```

# Description of the field Communication

```{r warning=F, message=F}
# load data
d_comm <- read.csv("data.csv")

# calculate average and typical sample size (n) per effect (k)
d_comm %<>%
  mutate(
    Mean.n.per.k = Mean.n / Mean.k,
    Median.n.per.k = Median.n / Median.k
    )

# calculate various effects sizes
d_comm %<>% 
  mutate(
    Median.etasq = eta_squared(r = Median.r),
    Median.d = cohens_d(r = Median.r),
    Median.or = odds_ratio(r = Median.r),
    Median.f = cohens_f(r = Median.r)
    )
  
# round values
d_comm %<>% 
  mutate_at(vars(SD.n, Mean.n.per.k, Median.n.per.k), funs(round(., 0))) %>% 
  mutate_at(vars(starts_with("Median")), funs(round(., 2)))

d_comm
```

# Power analyses for correlational designs

```{r warning=F, message=F}
# calculate power for actual and hypothetical correlational designs
d_pwr_cor <- 
  d_comm %>% 
  mutate(
    Median.pwr.r = pwr.r.test(Median.n.per.k, Median.r)$power,
    Median.pwr.10 = pwr.r.test(Median.n.per.k, .1)$power,
    Median.pwr.15 = pwr.r.test(Median.n.per.k, .15)$power,
    Median.pwr.20 = pwr.r.test(Median.n.per.k, .2)$power,
  ) %>% 
  mutate_at(vars(contains("pwr")), funs(round(., 2))) %>% 
  select(
    "Topic area" = Topic.area,
    "Power: r = Median r" = Median.pwr.r,
    "Power: r = .10" = Median.pwr.10,
    "Power: r = .15" = Median.pwr.15,
    "Power: r = .20" = Median.pwr.20
  ) %T>% 
  write.csv("table_power_correlations.csv", row.names = FALSE)

d_pwr_cor
```

# Power analyses for other designs

```{r warning=F, message=F}
# calculate medium power in the field for other designs
d_pwr <- 
  d_comm %>% 
  mutate(
    Median.pwr.r = pwr.r.test(n = Median.n.per.k, r = Median.r)$power,
    Median.pwr.t = pwr.t.test(n = Median.n.per.k / 2, d = Median.d, type = "two.sample")$power,
    Median.pwr.f2 = pwr.anova.test(k = 2, n = Median.n.per.k / 2, f = Median.f)$power,
    Median.pwr.f3 = pwr.anova.test(k = 3, n = Median.n.per.k / 3, f = Median.f)$power,
    Median.pwr.f4 = pwr.anova.test(k = 4, n = Median.n.per.k / 4, f = Median.f)$power
  ) %>% 
  mutate_at(vars(contains("pwr")), funs(round(., 2))) %>% 
  select(
    "Topic area" = Topic.area, 
    "Correlation" = Median.pwr.r,
    "t-test" = Median.pwr.t,
    "ANOVA 2 groups" = Median.pwr.f2,
    "ANOVA 3 groups" = Median.pwr.f3,
    "ANOVA 4 groups" = Median.pwr.f4
  ) %T>% 
  write.csv("table_power_other-designs.csv", row.names = FALSE)

d_pwr

```

